namespace UwpBackgroundTask
{
    [default_interface]
    runtimeclass ApplicationBackgroundTask : Windows.ApplicationModel.Background.IBackgroundTask
    {
        ApplicationBackgroundTask();
    }
}
